"""Generic single-database configuration."""

from alembic import op
import sqlalchemy as sa

revision = '85fe3dccc734'
down_revision = '0ed8975f4496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'language')
    # ### end Alembic commands ###
